### ISSUE TITLE
PAT-A-1010

### ISSUE THREAD

**Issue by nuaajeff** [GLAster/PAT-Advanced-Level#1]
同学你好：
参考你的PAT解集做A组1010题，发现如下问题：
对于比较函数的定义如下
`long long compare(long long a,string &b,int radix)`
但是事实上radix应该是一个long long型的。在二分查找的时候把long long型的mid作为radix参数传进来了。
但是如果把此处的int radix改成long long radix会导致有一个测试点过不去，如果按照你的写法就可以通过了。我想了很久不知道原因是什么，所以想问问你这是为什么？
谢谢！

**Comment by rflin** [comment]
你好，当初的确是没有注意到这个问题，在compare中，传进去的的确应该是long long，但是为什么传进去第三个测试点通不过，而int却过了？细想一下，问题可能出现在compare内部：当传radix过去时，因为radix可能过大，造成在for循环中的m值溢出，变为负数，这可能导致的后果便是，m<a，也就是说，逻辑上，我们认为radix太小了（返回的是-1），实际上并不是；那为什么int过了呢？因为int截取的是long long的一半，而最终得到的radix的确是比int类型的值要小的，所以对int来说，前面高位有没有都没关系的，因为反正最后结果都会返回1（int可能不溢出），所以结果正确

那么，如何解决这个问题呢，很简单，其实只需要在compare的循环中，if判定处加入m<0的溢出判断即可
代码已修改更新，感谢指出

**Comment by nuaajeff** [comment]
也感谢你的回答！
